const ACTIONS = {
  NEXT_QUESTION: "NEXT_QUESTION",
  PREV_QUESTION: "PREV_QUESTION",
  REDIRECT_TO: "REDIRECT_TO",
  SUBMIT_ANSWER: "SUBMIT_ANSWER",
  FINISH_ATTEMPT: "FINISH_ATTEMPT",
  CELEBRATIONS: "CELEBRATIONS",
  SUBMIT_ATTEMPT: "SUBMIT_ATTEMPT",
} as const;

export { ACTIONS };
