const ACTIONS = {
  NEXT_QUESTION: "NEXT_QUESTION",
  PREV_QUESTION: "PREV_QUESTION",
  REDIRECT_TO: "REDIRECT_TO",
  SUBMIT_ANSWER: "SUBMIT_ANSWER",
  FINISH_ATTEMPT: "FINISH_ATTEMPT",
  CELEBRATIONS: "CELEBRATIONS",
  SUBMIT_ATTEMPT: "SUBMIT_ATTEMPT",
  LEVEL_UP: "LEVEL_UP",
  SET_LOADING: "SET_LOADING",
  SET_DATA: "SET_DATA",
  SET_ERROR: "SET_ERROR",
  RESET_STATE: "RESET_STATE",
} as const;

export { ACTIONS };
